name: catalystaudio.co.uk
favicon: null
layout_spectrum: 0.7134124503936619
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292f3d'
    - '#d3dcd1'
    - '#545868'
    - '#75919d'
    - '#9ab9c4'
  brandStrength: 0.5
  lightness: 0.5868238774128258
  saturation: 0.5589147375430912
  rhythmicContrast: 0.38419789471663535
purpose: []
